# Generated by Django 5.0.1 on 2024-02-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('SS', 'LEGEND'), ('S', 'START'), ('A', 'ADVANCED'), ('B', 'ALMOST-ADVANCED'), ('C', 'INTERMEDIATE'), ('D', 'PRE-INTERMEDIATE'), ('E', 'BASIC')], default='E', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bi', models.CharField(max_length=14)),
                ('birthday', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
