# Generated by Django 5.0.1 on 2024-02-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_rename_natianality_teacher_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='bi',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bi',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
